[program:infimal-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/infimal/artisan queue:work database --queue=emails,default --sleep=3 --tries=5 --max-time=3600 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/infimal/storage/logs/worker.log
stopwaitsecs=3600
